# Generated by Django 2.2.5 on 2019-12-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WBBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestboard',
            name='accepted',
            field=models.CharField(choices=[(' PE ', 'Pending'), (' AC ', 'Accepted'), (' DE ', 'Denied')], max_length=2),
        ),
    ]
