# Generated by Django 2.2.5 on 2019-12-03 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WBBackend', '0002_auto_20191203_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestboard',
            old_name='accepted',
            new_name='status',
        ),
    ]
