# Generated by Django 2.2.5 on 2019-12-03 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WBBackend', '0003_auto_20191203_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WBBackend.Demand')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WBBackend.Offer')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WBBackend.RequestBoard')),
            ],
            options={
                'db_table': 'trip_details',
                'ordering': ['offer'],
            },
        ),
        migrations.CreateModel(
            name='TripChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WBBackend.Offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WBBackend.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('stop_time', models.TimeField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WBBackend.Offer')),
            ],
            options={
                'db_table': 'trip',
                'ordering': ['offer'],
            },
        ),
    ]
